version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: snowflake_customer_purchases
    description: "The total purchases for each customer in snowflake sample data"
    columns:
      - name: c_custkey
        description: "The unique customer id for this table"
        tests:
          - unique
          - not_null
      - name: c_name
        description: "The customer name for this table"
        tests:
          - unique
          - not_null
      - name: c_nationkey
        description: "The nation key for this table"
        tests:
          - unique
          - not_null

  - name: snowflake_nation_customer_count
    description: "The total number of customers for each nation in snowflake sample data"
    columns:
      - name: n_name
        description: "The nation name for this table"
        tests:
          - unique
          - not_null
      - name: n_nationkey
        description: "The nation key for this table"
        tests:
          - unique
          - not_null
